#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

sh .scripts/dwm_bar/bar.sh &
sh .scripts/dwm_bar/getinfo.sh &
xrdb ~/.Xresources &
xbindkeys -f ".config/xbindkeys/config/.xbindkeysrc"
nitrogen --restore &
picom -b &
udiskie -N &
mpd-discord-rpc &
openrgb --startminimized --profile "static-gold.orp" &

exec dwm
