#!/bin/bash
w="$(curl -s https://wttr.in/Brasilia?format=%h+%t'\n'%c 2> /dev/null \
    | sed "s/.*☀.*/󰖙/;s/.*☁.*/󰖐,/;s/.*⛅.*/󰖕/;s/.*⛈.*/󰙾/;s/.*✨.*//;s/.*❄.*/󰜗/;s/.*🌦.*/󰼳/;s/.*🌧.*/󰖗/;s/.*🌨.*/󰖘/;s/.*🌩.*/󰖓/;s/.*🌫.*/󰖑/" \
    | tr '\n' ' ')"
if [ $(echo $w | wc -c) -gt 15 ]; then w="Weather unavailable";fi
echo "$w"
